# -*- coding: utf-8 -*-
"""SocialMediaAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GbtDFYN0AIwas3BayDVzlsLfmX0r4plr
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display plots inside Jupyter Notebook
# %matplotlib inline

# Better looking plots
plt.style.use('ggplot')
sns.set_theme(style="whitegrid")

df = pd.read_csv("/content/Social Media Engagement Dataset.csv")

df.head(10)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.columns

df.info()

df.describe()

missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

df.duplicated().sum()

df["timestamp"] = pd.to_datetime(df["timestamp"])

df.info()

df["month"] = df["timestamp"].dt.month_name()
df["hour"] = df["timestamp"].dt.hour
df["date"] = df["timestamp"].dt.date
df["year"] = df["timestamp"].dt.year
df["is_weekend"] = df["day_of_week"].isin(["Saturday", "Sunday"])

df["total_engagement"] = (
    df["likes_count"] +
    df["comments_count"] +
    df["shares_count"]
)

# @title
df.to_csv("cleaned_social_media_data.csv", index=False)

platform_engagement = (
    df.groupby("platform")["total_engagement"]
      .mean()
      .sort_values(ascending=False)
)

print(platform_engagement)

plt.figure(figsize=(8,5))

sns.barplot(
    x=platform_engagement.index,
    y=platform_engagement.values,
    palette="viridis"
)

plt.title("Average Engagement by Platform")
plt.xlabel("Platform")
plt.ylabel("Average Total Engagement")

plt.show()

likes = (
    df.groupby("platform")["likes_count"]
      .mean()
      .sort_values(ascending=False)
)

plt.figure(figsize=(8,5))

sns.barplot(
    x=likes.index,
    y=likes.values,
    palette="rocket"
)

plt.title("Average Likes by Platform")
plt.ylabel("Average Likes")

plt.show()

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="sentiment_label",
    palette="Set2"
)

plt.title("Sentiment Distribution")

plt.show()

sentiment = (
    df.groupby("sentiment_label")["total_engagement"]
      .mean()
)

plt.figure(figsize=(7,5))

sns.barplot(
    x=sentiment.index,
    y=sentiment.values,
    palette="coolwarm"
)

plt.title("Average Engagement by Sentiment")

plt.show()

emotion = (
    df.groupby("emotion_type")["total_engagement"]
      .mean()
      .sort_values(ascending=False)
)

plt.figure(figsize=(10,5))

sns.barplot(
    x=emotion.index,
    y=emotion.values,
    palette="magma"
)

plt.xticks(rotation=45)

plt.title("Engagement by Emotion")

plt.show()

topic = (
    df.groupby("topic_category")["total_engagement"]
      .mean()
      .sort_values(ascending=False)
)

plt.figure(figsize=(10,6))

sns.barplot(
    x=topic.index,
    y=topic.values,
    palette="crest"
)

plt.xticks(rotation=45)

plt.title("Engagement by Topic Category")

plt.show()

day = (
    df.groupby("day_of_week")["total_engagement"]
      .mean()
)

order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

day = day.reindex(order)

plt.figure(figsize=(10,5))

sns.barplot(
    x=day.index,
    y=day.values,
    palette="Blues"
)

plt.title("Average Engagement by Day")

plt.show()

hour = (
    df.groupby("hour")["total_engagement"]
      .mean()
)

plt.figure(figsize=(12,5))

plt.plot(
    hour.index,
    hour.values,
    marker="o"
)

plt.title("Average Engagement by Posting Hour")

plt.xlabel("Hour")

plt.ylabel("Average Engagement")

plt.grid(True)

plt.show()

brand = (
    df.groupby("brand_name")["total_engagement"]
      .mean()
      .sort_values(ascending=False)
      .head(10)
)

plt.figure(figsize=(10,5))

sns.barplot(
    x=brand.values,
    y=brand.index,
    palette="flare"
)

plt.title("Top 10 Brands by Engagement")

plt.show()

campaign = (
    df.groupby("campaign_name")["total_engagement"]
      .mean()
      .sort_values(ascending=False)
      .head(10)
)

plt.figure(figsize=(10,5))

sns.barplot(
    x=campaign.values,
    y=campaign.index,
    palette="viridis"
)

plt.title("Top Campaigns")

plt.show()

corr = df[
    [
        "likes_count",
        "comments_count",
        "shares_count",
        "impressions",
        "engagement_rate",
        "sentiment_score",
        "toxicity_score",
        "total_engagement"
    ]
].corr()

plt.figure(figsize=(10,8))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    linewidths=0.5
)

plt.title("Correlation Heatmap")

plt.show()

top_posts = (
    df.sort_values("total_engagement", ascending=False)
      [["post_id",
        "platform",
        "topic_category",
        "total_engagement"]]
      .head(10)
)

print(top_posts)

# Total Posts
total_posts = len(df)

# Total Likes
total_likes = df["likes_count"].sum()

# Total Comments
total_comments = df["comments_count"].sum()

# Total Shares
total_shares = df["shares_count"].sum()

# Total Impressions
total_impressions = df["impressions"].sum()

# Average Engagement
average_engagement = df["total_engagement"].mean()

# Average Engagement Rate
average_engagement_rate = df["engagement_rate"].mean()

print("Total Posts:", total_posts)
print("Total Likes:", total_likes)
print("Total Comments:", total_comments)
print("Total Shares:", total_shares)
print("Total Impressions:", total_impressions)
print("Average Engagement:", round(average_engagement,2))
print("Average Engagement Rate:", round(average_engagement_rate,2))

plt.figure(figsize=(10,5))

sns.histplot(df["likes_count"], bins=30, kde=True)

plt.title("Distribution of Likes")

plt.show()

plt.figure(figsize=(10,5))

sns.histplot(df["comments_count"], bins=30, kde=True)

plt.title("Distribution of Comments")

plt.show()

plt.figure(figsize=(10,5))

sns.histplot(df["shares_count"], bins=30, kde=True)

plt.title("Distribution of Shares")

plt.show()

plt.figure(figsize=(10,5))

sns.histplot(df["engagement_rate"], bins=100)

plt.title("Engagement Rate Distribution")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["likes_count"])

plt.title("Outliers in Likes")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["comments_count"])

plt.title("Outliers in Comments")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["shares_count"])

plt.title("Outliers in Shares")

plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x="likes_count",
    y="shares_count",
    alpha=0.6
)

plt.title("Likes vs Shares")

plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x="likes_count",
    y="comments_count",
    alpha=0.6
)

plt.title("Likes vs Comments")

plt.show()

daily = (
    df.groupby("date")["total_engagement"]
      .mean()
)

plt.figure(figsize=(14,6))

plt.plot(daily.index, daily.values)

plt.title("Daily Engagement Trend")

plt.xticks(rotation=45)

plt.show()

top20 = (
    df.sort_values(
        "total_engagement",
        ascending=False
    ).head(20)
)

top20[
    [
        "post_id",
        "platform",
        "topic_category",
        "likes_count",
        "comments_count",
        "shares_count",
        "total_engagement"
    ]
]

highest_platform = (
    df.groupby("platform")["total_engagement"]
      .mean()
      .idxmax()
)

best_topic = (
    df.groupby("topic_category")["total_engagement"]
      .mean()
      .idxmax()
)

best_day = (
    df.groupby("day_of_week")["total_engagement"]
      .mean()
      .idxmax()
)

best_brand = (
    df.groupby("brand_name")["total_engagement"]
      .mean()
      .idxmax()
)

print("Best Platform :", highest_platform)
print("Best Topic :", best_topic)
print("Best Day :", best_day)
print("Best Brand :", best_brand)

